/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export declare function listProcesses(): Array<ProcessInfo>
export declare function getFocusedWindow(): FocusedWindow | null
export declare function focusWindowByPid(pid: number): boolean
export interface FocusedWindow {
  pid: number
  process: string
  processName: string
  path: string
  mainWindowTitle: string
  hasWindow: boolean
}
export interface ProcessInfo {
  pid: number
  process: string
  processName: string
  path: string
  mainWindowTitle: string
  hasWindow: boolean
}
